<#
.SYNOPSIS
  ดึงมาตรฐานจาก central-standards repo มาประกอบเป็น CLAUDE.md ของโปรเจกต์ปลายทาง

.DESCRIPTION
  อ่าน standards.json (source, ref, packs, output) แล้ว:
   1. clone repo กลางตาม ref (หรือใช้ path ในเครื่องถ้า source ชี้ไปโฟลเดอร์)
   2. ต่อ core/ + packs ที่เลือก
   3. เขียนลง output ภายในบล็อก marker (idempotent — รันซ้ำได้)

.EXAMPLE
  pwsh ./sync-standards.ps1 -Config ./standards.json
#>
[CmdletBinding()]
param(
  [string]$Config = "./standards.json"
)

$ErrorActionPreference = "Stop"

$BEGIN = "<!-- BEGIN central-standards (generated) -->"
$END   = "<!-- END central-standards (generated) -->"

function Read-Config([string]$path) {
  if (-not (Test-Path $path)) { throw "ไม่พบ config: $path" }
  return Get-Content -Raw -Path $path | ConvertFrom-Json
}

function Resolve-Source($source, $ref) {
  # ถ้า source เป็น path ในเครื่องที่มีอยู่ → ใช้ตรง ๆ (โหมดทดสอบ/offline)
  if (Test-Path $source) {
    return @{ Path = (Resolve-Path $source).Path; Temp = $null }
  }
  # ไม่งั้น clone แบบ shallow ตาม ref ไปยัง temp
  $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("central-standards-" + [guid]::NewGuid().ToString("N"))
  Write-Host "Cloning $source @ $ref ..."
  git clone --depth 1 --branch $ref $source $tmp 2>&1 | Out-Null
  if ($LASTEXITCODE -ne 0) { throw "git clone ล้มเหลว ($source @ $ref)" }
  return @{ Path = $tmp; Temp = $tmp }
}

function Build-Block($root, $packs) {
  $sb = [System.Text.StringBuilder]::new()
  [void]$sb.AppendLine($BEGIN)
  [void]$sb.AppendLine("<!-- generated by central-standards sync — DO NOT EDIT inside this block -->")
  [void]$sb.AppendLine("")

  # core ทั้งหมดก่อน
  foreach ($f in @("core/workflow.md", "core/conventions.md")) {
    $p = Join-Path $root $f
    if (Test-Path $p) {
      [void]$sb.AppendLine("<!-- core:$f -->")
      [void]$sb.AppendLine((Get-Content -Raw -Path $p).TrimEnd())
      [void]$sb.AppendLine("")
    }
  }

  # แต่ละ pack ที่เลือก
  foreach ($pack in $packs) {
    $p = Join-Path $root "packs/$pack/CLAUDE.md"
    if (-not (Test-Path $p)) { throw "ไม่พบ pack '$pack' ที่ $p" }
    [void]$sb.AppendLine("<!-- BEGIN pack:$pack -->")
    [void]$sb.AppendLine((Get-Content -Raw -Path $p).TrimEnd())
    [void]$sb.AppendLine("<!-- END pack:$pack -->")
    [void]$sb.AppendLine("")
  }

  [void]$sb.AppendLine($END)
  return $sb.ToString().TrimEnd() + "`n"
}

function Write-Output-File($outPath, $block) {
  $existing = ""
  if (Test-Path $outPath) { $existing = Get-Content -Raw -Path $outPath }

  if ($existing -match [regex]::Escape($BEGIN)) {
    # แทนที่เฉพาะบล็อก generated เดิม (ใช้ MatchEvaluator เลี่ยงปัญหา $-escaping ใน replacement)
    $pattern = "(?s)" + [regex]::Escape($BEGIN) + ".*?" + [regex]::Escape($END)
    $new = [regex]::Replace($existing, $pattern, { param($m) $block })
  } else {
    if ([string]::IsNullOrWhiteSpace($existing)) {
      $new = $block
    } else {
      $new = $existing.TrimEnd() + "`n`n" + $block
    }
  }
  Set-Content -Path $outPath -Value $new -Encoding utf8 -NoNewline
}

# ---- main ----
$cfg = Read-Config $Config
if (-not $cfg.packs) { throw "config ต้องมี 'packs' อย่างน้อย 1 ตัว" }
$ref = if ($cfg.ref) { $cfg.ref } else { "main" }
$out = if ($cfg.output) { $cfg.output } else { "CLAUDE.md" }

$src = Resolve-Source $cfg.source $ref
try {
  $block = Build-Block $src.Path $cfg.packs
  Write-Output-File $out $block
  Write-Host "OK — เขียน $out แล้ว (packs: $($cfg.packs -join ', ') @ $ref)"
}
finally {
  if ($src.Temp -and (Test-Path $src.Temp)) {
    Remove-Item -Recurse -Force $src.Temp
  }
}
