#!/usr/bin/env bash
#
# ดึงมาตรฐานจาก central-standards repo มาประกอบเป็น CLAUDE.md ของโปรเจกต์ปลายทาง
#
# อ่าน standards.json (source, ref, packs, output) แล้ว:
#   1. clone repo กลางตาม ref (หรือใช้ path ในเครื่องถ้า source ชี้ไปโฟลเดอร์)
#   2. ต่อ core/ + packs ที่เลือก
#   3. เขียนลง output ภายในบล็อก marker (idempotent — รันซ้ำได้)
#
# ต้องมี: git, jq
# usage: ./sync-standards.sh [./standards.json]

set -euo pipefail

CONFIG="${1:-./standards.json}"
BEGIN="<!-- BEGIN central-standards (generated) -->"
END="<!-- END central-standards (generated) -->"

command -v jq >/dev/null 2>&1 || { echo "ต้องติดตั้ง jq ก่อน" >&2; exit 1; }
[ -f "$CONFIG" ] || { echo "ไม่พบ config: $CONFIG" >&2; exit 1; }

SOURCE=$(jq -r '.source' "$CONFIG")
REF=$(jq -r '.ref // "main"' "$CONFIG")
OUT=$(jq -r '.output // "CLAUDE.md"' "$CONFIG")
mapfile -t PACKS < <(jq -r '.packs[]' "$CONFIG")
[ "${#PACKS[@]}" -gt 0 ] || { echo "config ต้องมี 'packs' อย่างน้อย 1 ตัว" >&2; exit 1; }

TMP=""
cleanup() { [ -n "$TMP" ] && [ -d "$TMP" ] && rm -rf "$TMP"; }
trap cleanup EXIT

if [ -d "$SOURCE" ]; then
  ROOT="$SOURCE"                       # โหมดทดสอบ/offline: ใช้ path ในเครื่อง
else
  TMP=$(mktemp -d)
  echo "Cloning $SOURCE @ $REF ..."
  git clone --depth 1 --branch "$REF" "$SOURCE" "$TMP" >/dev/null 2>&1
  ROOT="$TMP"
fi

# ---- ประกอบบล็อก generated ----
BLOCK_FILE=$(mktemp)
{
  echo "$BEGIN"
  echo "<!-- generated by central-standards sync — DO NOT EDIT inside this block -->"
  echo ""
  for f in core/workflow.md core/conventions.md; do
    if [ -f "$ROOT/$f" ]; then
      echo "<!-- core:$f -->"
      cat "$ROOT/$f"
      echo ""
    fi
  done
  for pack in "${PACKS[@]}"; do
    p="$ROOT/packs/$pack/CLAUDE.md"
    [ -f "$p" ] || { echo "ไม่พบ pack '$pack' ที่ $p" >&2; exit 1; }
    echo "<!-- BEGIN pack:$pack -->"
    cat "$p"
    echo "<!-- END pack:$pack -->"
    echo ""
  done
  echo "$END"
} > "$BLOCK_FILE"

# ---- merge เข้า output (idempotent) ----
if [ -f "$OUT" ] && grep -qF "$BEGIN" "$OUT"; then
  # แทนที่บล็อกเดิมระหว่าง BEGIN..END ด้วยบล็อกใหม่
  awk -v begin="$BEGIN" -v end="$END" -v blockfile="$BLOCK_FILE" '
    $0 == begin { while ((getline line < blockfile) > 0) print line; skip=1; next }
    $0 == end   { skip=0; next }
    skip != 1   { print }
  ' "$OUT" > "$OUT.tmp"
  mv "$OUT.tmp" "$OUT"
else
  if [ -f "$OUT" ] && [ -s "$OUT" ]; then
    printf '\n\n' >> "$OUT"
    cat "$BLOCK_FILE" >> "$OUT"
  else
    cat "$BLOCK_FILE" > "$OUT"
  fi
fi
rm -f "$BLOCK_FILE"

echo "OK — เขียน $OUT แล้ว (packs: ${PACKS[*]} @ $REF)"
